project:
  type: website
  output-dir: docs
resources:
    - "../../assets/**"
website:
  title: "Austin Lin's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Projects
      - href: pages/about.qmd
        text: About Me
      - href: assets/ALin Resume.pdf
        text: Resume


  page-footer:
    right: "Built with [Quarto](https://quarto.org)"
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: show
    code-summary: "Show code"
