project:
  type: website
  output-dir: docs

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Projects
      - href: pages/about.qmd
        text: About Me

  page-footer:
    right: "Built with [Quarto](https://quarto.org)"
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
